name: Automatizar Dosis de Ciencia

on:
  schedule:
    # Se ejecuta a las 8:00 AM (UTC) los lunes (1), miércoles (3) y viernes (5)
    - cron: '0 8 * * 1,3,5'
  
  workflow_dispatch:

jobs:
  generar-infografia:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias del sistema y Python
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-roboto
        pip install Pillow requests

    - name: Ejecutar generador de infografías
      run: python main.py
